###################################################
/stix/geo/att false
/stix/geo/cad false
/stix/geo/grids true
/run/initialize
/process/em/fluo true

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 10 mm
/gps/pos/centre -1200 140.6  90.2 mm #center 
/gps/pos/rot1  0 0 1
/gps/pos/rot2  0 -1 0
/gps/direction 1 0 0 

/gps/ene/type Lin
/gps/ene/min 4 keV
/gps/ene/max  150 keV
/gps/ene/intercept 1
/gps/ene/gradient 0

/run/beamOn 10000000
