/run/initialize
/control/verbose 0
/tracking/verbose 0


/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 90 mm
/gps/pos/centre 0 0  1000 mm
#/gps/pos/radius 90 mm

#/gps/pos/centre 0 0  1000 mm
#/gps/direction 0 0 -1

/gps/particle proton

#/gps/pos/radius 15 mm
/gps/ene/type Lin
/gps/ene/min 1 MeV
/gps/ene/max  100 MeV
/gps/ene/intercept 1
/gps/ene/gradient 0

#/gps/ene/type Pow
#/gps/ene/min 10 keV
#/gps/ene/max  2 MeV
#/gps/ene/alpha -2

/run/beamOn 10000000
