###################################################
/stix/geo/cad false
/stix/geo/grids false
/stix/geo/att false
/run/initialize
/process/em/fluo true



/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 90 mm
/gps/pos/centre -1200 103  127.5 mm #center 
/gps/pos/rot1  0 0 1
/gps/pos/rot2  0 -1 0
/gps/direction 1 0 0 



/gps/ene/type Pow
/gps/ene/alpha -5
/gps/ene/min 4 keV
/gps/ene/max 200 keV


/run/beamOn 1000000
