###################################################

/stix/geo/cad false
/stix/geo/grids false
/stix/geo/att false
/run/initialize
/process/em/fluo true

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 1 mm
/gps/pos/halfy 1 mm
/gps/pos/centre -1200 168.9 166.3 mm
#/gps/pos/rot1  0 0 1
#/gps/pos/rot2  0 -1 0
#/gps/position -1200 168.9 166.3 mm # detector 0, pixel 0
/gps/direction 1 0 0 

/gps/ene/type Lin
/gps/ene/min 4 keV
/gps/ene/max  150 keV
/gps/ene/intercept 1
/gps/ene/gradient 0


/run/beamOn 1000000
