###################################################
/stix/geo/att false
/stix/geo/cad true
/stix/geo/grids true
/run/initialize
/process/em/fluo true

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 90 mm
/gps/pos/centre -1200 103  127.5 mm #center 
/gps/pos/rot1  0 0 1
/gps/pos/rot2  0 -1 0
/gps/direction 1 0 0 

/gps/ene/type Lin
/gps/ene/min 4 keV
/gps/ene/max  250 keV
/gps/ene/intercept 1
/gps/ene/gradient 0

/run/beamOn 100000000
